site_name: Genetic Data Processing Workflow

nav:
  - Home: index.md
          docs/graphviz.png
  - Pipeline Overview: overview.md
  - Data Collection: data_collection.md
  - Data Processing: data_processing.md
  - Variant Analysis: variant_analysis.md
  - Results & Interpretation: results.md
  - Summary: all.md
  - API & References:
      - Functions: functions.md

plugins:
  - search
  - mkdocstrings
